import "./globals.css";
import { Pattaya } from "next/font/google";

const pattaya = Pattaya({ weight: "400", subsets: ["latin"], display: "swap" });

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={pattaya.className}>
      <body>{children}</body>
    </html>
  );
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
